name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: cuckoom
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npm run build

      - name: Deploy to server via cp
        run: |
          rm -rf /var/www/cuckoom.com/* && cp -r ./public/* /var/www/cuckoom.com/ && sudo systemctl restart nginx
