name: Deploy Blog

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: cuckoom
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Generate static files
        run: npm run build

      - name: Deploy to server via rsync
        run: |
          rsync -avz --delete ./public/ root@47.98.148.158:/var/www/cuckoom.com/
